article: https://github.com/bigclownlabs/bcf-generic-node/blob/master/README.md
images:
  - title: Core Module
    url: https://www.hardwario.com/modules/Modules_382x324_Core.png
assembly:
  - name: BigClown Core Module
  - name: BigClown Barometer Tag
    optional: true
  - name: BigClown Battery Module  
    optional: true
  - name: BigClown Button Module
    optional: true
  - name: BigClown Climate Module
    optional: true
  - name: BigClown CO2 Module
    optional: true
  - name: BigClown Humidity Tag
    optional: true
  - name: BigClown LCD Module
    optional: true
  - name: BigClown Lux Meter Tag
    optional: true
  - name: BigClown Mini Battery Module  
    optional: true
  - name: BigClown PIR Module
    optional: true
  - name: BigClown Power Module
    optional: true
  - name: BigClown Relay Module
    optional: true
  - name: BigClown Sensor Module
    optional: true
  - name: BigClown Tag Module
    optional: true
  - name: BigClown Temperature Tag
    optional: true
