article: https://github.com/bigclownlabs/bcf-generic-node/blob/master/README.md
images:
  - title: Core Module
    url: https://www.hardwario.com/modules/Modules_382x324_Core.png
assembly:
  - name: HARDWARIO Core Module
  - name: HARDWARIO Barometer Tag
    optional: true
  - name: HARDWARIO Battery Module  
    optional: true
  - name: HARDWARIO Button Module
    optional: true
  - name: HARDWARIO Climate Module
    optional: true
  - name: HARDWARIO CO2 Module
    optional: true
  - name: HARDWARIO Humidity Tag
    optional: true
  - name: HARDWARIO LCD Module
    optional: true
  - name: HARDWARIO Lux Meter Tag
    optional: true
  - name: HARDWARIO Mini Battery Module  
    optional: true
  - name: HARDWARIO PIR Module
    optional: true
  - name: HARDWARIO Power Module
    optional: true
  - name: HARDWARIO Relay Module
    optional: true
  - name: HARDWARIO Sensor Module
    optional: true
  - name: HARDWARIO Tag Module
    optional: true
  - name: HARDWARIO Temperature Tag
    optional: true
